### PR TITLE
Fix translate error message

### LINKED ISSUE #229: translate error message is bad
**Describe the bug**
Attempted to use the old translate method of translation with

`/nc translate hello french`

and got
```

/nc translate hello french

Nimbella CommanderAPP  4:01 PM
Error: Cannot read property 'status' of undefined
```

**To Reproduce**
run /nc translate hello french

**Expected behavior**
should say the language is bad and put an example language

**Messaging Platform (please complete the following information):**
 - Messaging Platform: all
 - Commander Version: not applicable

### PR DESCRIPTION
**Pull request by dengliming**
fixes [https://github.com/nimbella/command-sets/issues/229](https://github.com/nimbella/command-sets/issues/229)

image

### CODE REVIEW

File: translate/packages/translate/translate/index.js [hunk 1]
```diff
@@ -1,6 +1,17 @@
 // jshint esversion: 9
 
 const translator = 'https://translate.googleapis.com/translate_a/single';
+let ISO6391;
+async function install(pkgs) {
```
Comment (satyarohith) [inline translate/packages/translate/translate/index.js]: This is no longer needed. You can mention your package in packages.json to add an external dependency. Example: https://github.com/nimbella/command-sets/blob/b85860daa9d3d16c0f6b900b88670b78f4fdb392/translate/packages/translate/translate/package.json#L11

File: translate/packages/translate/translate/index.js [hunk 2]
```diff
@@ -52,6 +63,10 @@ const fail = msg => {
  */
 async function _command(params, commandText, secrets = {}) {
   const axios = require('axios');
+  if (!ISO6391) {
```
Comment (satyarohith) [inline translate/packages/translate/translate/index.js]: Replace the if block with this: 

```js
const ISO6391 = require('iso-639-1');
```

File: translate/packages/translate/translate/index.js [hunk 3]
```diff
@@ -65,8 +80,10 @@ async function _command(params, commandText, secrets = {}) {
 
   try {
     if (targetLang.length != 2) {
-      const ISO6391 = require('iso-639-1');
       targetLang = ISO6391.getCode(targetLang);
+      if (!targetLang) {
+        return {response_type: 'in_channel', text: languageHelp};
```
Comment (satyarohith) [inline translate/packages/translate/translate/index.js]:
```suggestion
        return {response_type: 'ephemeral', text: languageHelp};
```

Since this is error/help text, ephemeral makes more sense.

**Review by satyarohith — CHANGES_REQUESTED** [review]
Thanks, @dengliming! I've left a few comments. :)

File: translate/packages/translate/translate/index.js (hunk 1 above)
Comment (dengliming) [reply translate/packages/translate/translate/index.js]: Hey~ I'm a little confused that How do I test this command in Nimbella? If I remove it it will get `Cannot find module iso-639-1`

Comment (satyarohith) [reply translate/packages/translate/translate/index.js]: Here's how you can test it: 
- Push the changes to your branch
- Delete the `translate` command from your Slack workspace using `/nc command_delete translate`
- Install your version of `translate` by running `/nc csm_install https://raw.githubusercontent.com/dengliming/command-sets/fix_message/translate/commands.yaml`.

Alternatively, check out https://github.com/nimbella/commander-cli, it helps you develop and test commands directly from the terminal without having to go Slack.

Comment (dengliming) [reply translate/packages/translate/translate/index.js]: @satyarohith 👍  Thanks a lot.

**Review by rabbah — APPROVED** [review]

**Review by niks3089 — APPROVED** [review]
