### PR TITLE
[BlueJeans] Update `bluejeans` command with new docs

### LINKED ISSUE #64: /dapp bluejeans fails
```
Initialization has failed due to: SyntaxError: Unexpected identifier
    at initializeActionHandler (/nodejsAction/runner.js:57:87)
    at doInit (/nodejsAction/src/service.js:176:16)
    at initCode (/nodejsAction/src/service.js:95:24)
    at /nodejsAction/platform/platform.js:125:17
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at next (/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at /node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/node_modules/express/lib/router/index.js:335:12)
```

### PR DESCRIPTION
**Pull request by satyarohith**
Closes #64

### CODE REVIEW

File: bluejeans/src/bluejeans.js [hunk 1]
```diff
@@ -15,26 +15,38 @@ async function _command(params, commandText, secrets = {}) {
...
+After you've the credentials, we need two secrets named \`bluejeansAppKey\` & \`bluejeansAppSecret\` with your credentials as their values. You can create them by running \`/nc secret_create\`.
 
 ## Usage
 
 To create a meeting with \`joe@example.com\` & \`judy@example.com\`:
 \`\`\`sh
 /dapp bluejeans_create -title "A new beginning" -emails "joe@example.com,judy@example.com" -start "03/01/20 18:00" -end "03/01/20 18:30'
 \`\`\`
-Where date is in `mm/dd/yy` format and time is in UTC.
+Where date is in \`mm/dd/yy\` format and time is in UTC.
```
Comment (satyarohith) [inline bluejeans/src/bluejeans.js:32]: Closes #64

**Review by niks3089 — APPROVED** [review]
